[phases.setup]
nixpkgsPackages = ["php83", "composer", "nodejs_20", "npm"]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[phases.start]
cmd = "sh -c 'touch /tmp/database.sqlite && php artisan serve --host 0.0.0.0 --port $PORT'"
